// <auto-generated />
namespace Ncb.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _12312356 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12312356));
        
        string IMigrationMetadata.Id
        {
            get { return "201708111520300_12312356"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
